{% set name = "pyclesperanto-prototype" %}
{% set version = "0.24.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyclesperanto_prototype-{{ version }}.tar.gz
  sha256: 3c27455ff57374cf8283e9c7bc02a8c14f2cb2685cb68730ff8578426280e437

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy !=1.19.4
    - platformdirs
    - pyopencl
    - python >={{ python_min }}
    - scikit-image >=0.18.0, !=0.20.0
    - toolz
    - transforms3d

test:
  imports:
    - pyclesperanto_prototype
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pocl  # [not win]
    - oclgrind  # [win]
    - python {{ python_min }}

about:
  home: https://github.com/clEsperanto/pyclesperanto_prototype
  summary: GPU-accelerated image processing in python using OpenCL
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
