{% set name = "pyclesperanto-prototype" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyclesperanto_prototype-{{ version }}.tar.gz
  sha256: 4beeae32c9d4f36b19ecf74b31d8d3f747e9286aedbde8e6f7237b65189fde98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy !=1.19.4
    - platformdirs
    - pyopencl
    - python >=3.6
    - scikit-image >=0.18.0
    - toolz
    - transforms3d

test:
  imports:
    - pyclesperanto_prototype
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pocl  # [not win]
    - oclgrind  # [win]

about:
  home: https://github.com/clEsperanto/pyclesperanto_prototype
  summary: GPU-accelerated image processing in python using OpenCL
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
